### ISSUE TITLE
Parametro message 

### ISSUE THREAD

**Issue by raulbt** [Arquisoft/voters_3a#10]
No entiendo como se genera el parametro message de los metodos de MainController.java.

Intentaba crear el metodo post para el cambio de contraseña pero no se que el message sea un ChangePass con los parametros del formulario en lugar de un UserPass.

Por lo demas la unica modificacion de codigo y no añadido que hice fue en el .js el boton de voter info ya no llama a /usr , sino a mi nuevo /usr2 (solo hay que quitar ese 2 para volver otra vez a como antes).

**Comment by davidglezz** [comment]
el framework lo genera automaticamente a traves de los datos pasados en la peticion http
