### ISSUE TITLE
Familiarizarse con Spring Boot

### ISSUE THREAD

**Issue by raulbt** [Arquisoft/voters_3a#2]
Os recomiendo consultar la documentación de _Spring Boot_ directamente, ya que esta muy completa. 
Para ir mas rápido aquí tenéis el [link](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/)
Especialmente el **punto 3 de primeros pasos** que tiene un tutorial y unos ejemplos bastante didácticos. 

Ademas el **punto 4** quizá sea interesante las partes de integración con _Maven_, aunque aun no las he probado.

**Comment by davidglezz** [comment]
getting-started-first-application: 
https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-first-application.html
aunque creo que esto ya estaría todo en el esqueleto, pero por si alguien anda perdido.
