### ISSUE TITLE
Familiarizarse con Maven

### ISSUE THREAD

**Issue by raulbt** [Arquisoft/voters_3a#3]
A pesar de que en el _Issues_ de **Familiarizarse con Spring Boot** ya puse un _link_ a su documentación en el cual viene como usar _Maven_ integrado en el _framework_, encontré en la misma web de _Spring_ un pequeño [tutorial para inicializarse en el manejo de Maven](https://spring.io/guides/gs/maven/) directamente por linea de comando.

**Comment by AmirHT** [comment]
Link dado en clase: http://search.maven.org/
