### ISSUE TITLE
Instalar entorno de trabajo. 

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/voters_3a#4]
En clase se recomendó el uso de un Eclipse STS con los plug in necesarios. También hay que instalar github ya sea en la versión de escritorio o en la de linea comando. 

https://spring.io/tools/sts/all

**Comment by davidglezz** [comment]
En el wiki actualice la página con enlaces a las herramientas.
https://github.com/Arquisoft/voters_3a/wiki/Info-herramientas

**Comment by AmirHT** [comment]
solo falta carlos por confirmar que tiene todo ok para trabajar. Cuando lo tengas, cierra la tarea :D

**Comment by Palaskan** [comment]
perdonad que no me había enterado y aquí no suelo entrar y se me olvida, para trabajar supongo que si tengo todas las herramientas para ello, aunque no sepa muy bien que hacer, lo que habéis estado haciendo no lo entiendo muy bien, el martes os veré y os pregunto si eso para entender algo
