### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/voters_3a#6]
¿Pedir al otro grupo o hacer nosotros una pequeña de pruebas? Hablar con el otro grupo y ver solución.

**Comment by davidglezz** [comment]
cuando la tengan, nos pasan el script de creación de la tabla, asi ya no hay problema de nombre de tabla y columnas y tipos de datos...
Queda pendiente.

**Comment by davidglezz** [comment]
ya la tenemos!
https://github.com/Arquisoft/censuses_3a/blob/master/src/main/java/es/uniovi/asw/model/Voter.java
habría que revisar si cumple la especificación.

**Comment by AmirHT** [comment]
han cambiado de lo que nos han dicho que usarían... hay que hablar con ellos o cotillear su git :dancers:
